with seed as (
    select *
    from jsonb_to_recordset(
        $json$
        [
          {"name":"Sentadilla con barra","muscle_group":"Pierna","slug":"sentadilla-con-barra","default_metric":"weight"},
          {"name":"Sentadilla con mancuernas","muscle_group":"Pierna","slug":"sentadilla-con-mancuernas","default_metric":"weight"},
          {"name":"Sentadilla en multipower","muscle_group":"Pierna","slug":"sentadilla-en-multipower","default_metric":"weight"},
          {"name":"Sentadilla frontal con barra","muscle_group":"Pierna","slug":"sentadilla-frontal-con-barra","default_metric":"weight"},
          {"name":"Sentadilla frontal con mancuernas","muscle_group":"Pierna","slug":"sentadilla-frontal-con-mancuernas","default_metric":"weight"},
          {"name":"Sentadilla búlgara con mancuernas","muscle_group":"Pierna","slug":"sentadilla-bulgara-con-mancuernas","default_metric":"weight"},
          {"name":"Sentadilla hack en máquina","muscle_group":"Pierna","slug":"sentadilla-hack-en-maquina","default_metric":"weight"},
          {"name":"Prensa de piernas inclinada","muscle_group":"Pierna","slug":"prensa-de-piernas-inclinada","default_metric":"weight"},
          {"name":"Prensa de piernas horizontal","muscle_group":"Pierna","slug":"prensa-de-piernas-horizontal","default_metric":"weight"},
          {"name":"Peso muerto con barra","muscle_group":"Pierna","slug":"peso-muerto-con-barra","default_metric":"weight"},
          {"name":"Peso muerto con mancuernas","muscle_group":"Pierna","slug":"peso-muerto-con-mancuernas","default_metric":"weight"},
          {"name":"Peso muerto rumano con barra","muscle_group":"Pierna","slug":"peso-muerto-rumano-con-barra","default_metric":"weight"},
          {"name":"Peso muerto rumano con mancuernas","muscle_group":"Pierna","slug":"peso-muerto-rumano-con-mancuernas","default_metric":"weight"},
          {"name":"Peso muerto sumo con barra","muscle_group":"Pierna","slug":"peso-muerto-sumo-con-barra","default_metric":"weight"},
          {"name":"Zancadas con mancuernas","muscle_group":"Pierna","slug":"zancadas-con-mancuernas","default_metric":"weight"},
          {"name":"Zancadas con barra","muscle_group":"Pierna","slug":"zancadas-con-barra","default_metric":"weight"},
          {"name":"Zancadas caminando con mancuernas","muscle_group":"Pierna","slug":"zancadas-caminando-con-mancuernas","default_metric":"weight"},
          {"name":"Zancadas inversas con barra","muscle_group":"Pierna","slug":"zancadas-inversas-con-barra","default_metric":"weight"},
          {"name":"Step-up con mancuernas","muscle_group":"Pierna","slug":"step-up-con-mancuernas","default_metric":"weight"},
          {"name":"Step-up con barra","muscle_group":"Pierna","slug":"step-up-con-barra","default_metric":"weight"},
          {"name":"Extensión de piernas en máquina","muscle_group":"Pierna","slug":"extension-de-piernas-en-maquina","default_metric":"weight"},
          {"name":"Curl femoral tumbado en máquina","muscle_group":"Pierna","slug":"curl-femoral-tumbado-en-maquina","default_metric":"weight"},
          {"name":"Curl femoral sentado en máquina","muscle_group":"Pierna","slug":"curl-femoral-sentado-en-maquina","default_metric":"weight"},
          {"name":"Curl femoral de pie en máquina","muscle_group":"Pierna","slug":"curl-femoral-de-pie-en-maquina","default_metric":"weight"},
          {"name":"Hip thrust con barra","muscle_group":"Pierna","slug":"hip-thrust-con-barra","default_metric":"weight"},
          {"name":"Hip thrust en máquina","muscle_group":"Pierna","slug":"hip-thrust-en-maquina","default_metric":"weight"},
          {"name":"Puente de glúteos con peso","muscle_group":"Pierna","slug":"puente-de-gluteos-con-peso","default_metric":"weight"},
          {"name":"Patada de glúteo en polea","muscle_group":"Pierna","slug":"patada-de-gluteo-en-polea","default_metric":"weight"},
          {"name":"Patada de glúteo en máquina","muscle_group":"Pierna","slug":"patada-de-gluteo-en-maquina","default_metric":"weight"},
          {"name":"Abducción de cadera en máquina","muscle_group":"Pierna","slug":"abduccion-de-cadera-en-maquina","default_metric":"weight"},
          {"name":"Aducción de cadera en máquina","muscle_group":"Pierna","slug":"aduccion-de-cadera-en-maquina","default_metric":"weight"},
          {"name":"Elevación de talones de pie con barra","muscle_group":"Pierna","slug":"elevacion-de-talones-de-pie-con-barra","default_metric":"weight"},
          {"name":"Elevación de talones en máquina","muscle_group":"Pierna","slug":"elevacion-de-talones-en-maquina","default_metric":"weight"},
          {"name":"Elevación de talones sentado","muscle_group":"Pierna","slug":"elevacion-de-talones-sentado","default_metric":"weight"},
          {"name":"Press de banca con barra","muscle_group":"Pecho","slug":"press-de-banca-con-barra","default_metric":"weight"},
          {"name":"Press de banca con mancuernas","muscle_group":"Pecho","slug":"press-de-banca-con-mancuernas","default_metric":"weight"},
          {"name":"Press inclinado con barra","muscle_group":"Pecho","slug":"press-inclinado-con-barra","default_metric":"weight"},
          {"name":"Press inclinado con mancuernas","muscle_group":"Pecho","slug":"press-inclinado-con-mancuernas","default_metric":"weight"},
          {"name":"Press declinado con barra","muscle_group":"Pecho","slug":"press-declinado-con-barra","default_metric":"weight"},
          {"name":"Press declinado con mancuernas","muscle_group":"Pecho","slug":"press-declinado-con-mancuernas","default_metric":"weight"},
          {"name":"Press en máquina convergente","muscle_group":"Pecho","slug":"press-en-maquina-convergente","default_metric":"weight"},
          {"name":"Press en multipower","muscle_group":"Pecho","slug":"press-en-multipower","default_metric":"weight"},
          {"name":"Aperturas con mancuernas en banco plano","muscle_group":"Pecho","slug":"aperturas-con-mancuernas-en-banco-plano","default_metric":"weight"},
          {"name":"Aperturas con mancuernas en banco inclinado","muscle_group":"Pecho","slug":"aperturas-con-mancuernas-en-banco-inclinado","default_metric":"weight"},
          {"name":"Aperturas en máquina (pec deck)","muscle_group":"Pecho","slug":"aperturas-en-maquina-pec-deck","default_metric":"weight"},
          {"name":"Cruces en polea alta","muscle_group":"Pecho","slug":"cruces-en-polea-alta","default_metric":"weight"},
          {"name":"Cruces en polea media","muscle_group":"Pecho","slug":"cruces-en-polea-media","default_metric":"weight"},
          {"name":"Cruces en polea baja","muscle_group":"Pecho","slug":"cruces-en-polea-baja","default_metric":"weight"},
          {"name":"Pullover con mancuerna","muscle_group":"Pecho","slug":"pullover-con-mancuerna","default_metric":"weight"},
          {"name":"Pullover en polea","muscle_group":"Pecho","slug":"pullover-en-polea","default_metric":"weight"},
          {"name":"Flexiones estándar","muscle_group":"Pecho","slug":"flexiones-estandar","default_metric":"weight"},
          {"name":"Flexiones con manos elevadas","muscle_group":"Pecho","slug":"flexiones-con-manos-elevadas","default_metric":"weight"},
          {"name":"Flexiones con pies elevados","muscle_group":"Pecho","slug":"flexiones-con-pies-elevados","default_metric":"weight"},
          {"name":"Flexiones lastradas","muscle_group":"Pecho","slug":"flexiones-lastradas","default_metric":"weight"},
          {"name":"Dominadas pronas","muscle_group":"Espalda","slug":"dominadas-pronas","default_metric":"weight"},
          {"name":"Dominadas supinas","muscle_group":"Espalda","slug":"dominadas-supinas","default_metric":"weight"},
          {"name":"Dominadas neutras","muscle_group":"Espalda","slug":"dominadas-neutras","default_metric":"weight"},
          {"name":"Dominadas lastradas","muscle_group":"Espalda","slug":"dominadas-lastradas","default_metric":"weight"},
          {"name":"Dominadas asistidas en máquina","muscle_group":"Espalda","slug":"dominadas-asistidas-en-maquina","default_metric":"weight"},
          {"name":"Jalón al pecho agarre ancho","muscle_group":"Espalda","slug":"jalon-al-pecho-agarre-ancho","default_metric":"weight"},
          {"name":"Jalón al pecho agarre cerrado","muscle_group":"Espalda","slug":"jalon-al-pecho-agarre-cerrado","default_metric":"weight"},
          {"name":"Jalón al pecho agarre neutro","muscle_group":"Espalda","slug":"jalon-al-pecho-agarre-neutro","default_metric":"weight"},
          {"name":"Jalón tras nuca","muscle_group":"Espalda","slug":"jalon-tras-nuca","default_metric":"weight"},
          {"name":"Remo con barra pronado","muscle_group":"Espalda","slug":"remo-con-barra-pronado","default_metric":"weight"},
          {"name":"Remo con barra supino","muscle_group":"Espalda","slug":"remo-con-barra-supino","default_metric":"weight"},
          {"name":"Remo con mancuerna a una mano","muscle_group":"Espalda","slug":"remo-con-mancuerna-a-una-mano","default_metric":"weight"},
          {"name":"Remo en polea baja agarre estrecho","muscle_group":"Espalda","slug":"remo-en-polea-baja-agarre-estrecho","default_metric":"weight"},
          {"name":"Remo en polea baja agarre ancho","muscle_group":"Espalda","slug":"remo-en-polea-baja-agarre-ancho","default_metric":"weight"},
          {"name":"Remo en máquina convergente","muscle_group":"Espalda","slug":"remo-en-maquina-convergente","default_metric":"weight"},
          {"name":"Remo en T con barra","muscle_group":"Espalda","slug":"remo-en-t-con-barra","default_metric":"weight"},
          {"name":"Pullover en polea alta","muscle_group":"Espalda","slug":"pullover-en-polea-alta","default_metric":"weight"},
          {"name":"Pullover en máquina","muscle_group":"Espalda","slug":"pullover-en-maquina","default_metric":"weight"},
          {"name":"Peso muerto convencional","muscle_group":"Espalda","slug":"peso-muerto-convencional","default_metric":"weight"},
          {"name":"Hiperextensiones en banco","muscle_group":"Espalda","slug":"hiperextensiones-en-banco","default_metric":"weight"},
          {"name":"Face pull en polea","muscle_group":"Espalda","slug":"face-pull-en-polea-espalda","default_metric":"weight"},
          {"name":"Curl con barra recta","muscle_group":"Biceps","slug":"curl-con-barra-recta","default_metric":"weight"},
          {"name":"Curl con barra Z","muscle_group":"Biceps","slug":"curl-con-barra-z","default_metric":"weight"},
          {"name":"Curl con mancuernas alterno","muscle_group":"Biceps","slug":"curl-con-mancuernas-alterno","default_metric":"weight"},
          {"name":"Curl con mancuernas simultáneo","muscle_group":"Biceps","slug":"curl-con-mancuernas-simultaneo","default_metric":"weight"},
          {"name":"Curl martillo con mancuernas","muscle_group":"Biceps","slug":"curl-martillo-con-mancuernas","default_metric":"weight"},
          {"name":"Curl martillo en polea","muscle_group":"Biceps","slug":"curl-martillo-en-polea","default_metric":"weight"},
          {"name":"Curl concentrado con mancuerna","muscle_group":"Biceps","slug":"curl-concentrado-con-mancuerna","default_metric":"weight"},
          {"name":"Curl en banco inclinado con mancuernas","muscle_group":"Biceps","slug":"curl-en-banco-inclinado-con-mancuernas","default_metric":"weight"},
          {"name":"Curl en banco predicador con barra","muscle_group":"Biceps","slug":"curl-en-banco-predicador-con-barra","default_metric":"weight"},
          {"name":"Curl en banco predicador con mancuerna","muscle_group":"Biceps","slug":"curl-en-banco-predicador-con-mancuerna","default_metric":"weight"},
          {"name":"Curl en polea baja","muscle_group":"Biceps","slug":"curl-en-polea-baja","default_metric":"weight"},
          {"name":"Curl 21 con barra","muscle_group":"Biceps","slug":"curl-21-con-barra","default_metric":"weight"},
          {"name":"Fondos en paralelas","muscle_group":"Triceps","slug":"fondos-en-paralelas","default_metric":"weight"},
          {"name":"Fondos en máquina asistida","muscle_group":"Triceps","slug":"fondos-en-maquina-asistida","default_metric":"weight"},
          {"name":"Extensión en polea con barra","muscle_group":"Triceps","slug":"extension-en-polea-con-barra","default_metric":"weight"},
          {"name":"Extensión en polea con cuerda","muscle_group":"Triceps","slug":"extension-en-polea-con-cuerda","default_metric":"weight"},
          {"name":"Extensión en polea agarre inverso","muscle_group":"Triceps","slug":"extension-en-polea-agarre-inverso","default_metric":"weight"},
          {"name":"Press francés con barra","muscle_group":"Triceps","slug":"press-frances-con-barra","default_metric":"weight"},
          {"name":"Press francés con mancuernas","muscle_group":"Triceps","slug":"press-frances-con-mancuernas","default_metric":"weight"},
          {"name":"Press cerrado con barra","muscle_group":"Triceps","slug":"press-cerrado-con-barra","default_metric":"weight"},
          {"name":"Press cerrado en multipower","muscle_group":"Triceps","slug":"press-cerrado-en-multipower","default_metric":"weight"},
          {"name":"Patada de tríceps con mancuerna","muscle_group":"Triceps","slug":"patada-de-triceps-con-mancuerna","default_metric":"weight"},
          {"name":"Extensión por encima de la cabeza con mancuerna","muscle_group":"Triceps","slug":"extension-por-encima-de-la-cabeza-con-mancuerna","default_metric":"weight"},
          {"name":"Extensión por encima de la cabeza en polea","muscle_group":"Triceps","slug":"extension-por-encima-de-la-cabeza-en-polea","default_metric":"weight"},
          {"name":"Extensión en máquina","muscle_group":"Triceps","slug":"extension-en-maquina","default_metric":"weight"},
          {"name":"Press militar con barra","muscle_group":"Hombro","slug":"press-militar-con-barra","default_metric":"weight"},
          {"name":"Press militar con mancuernas","muscle_group":"Hombro","slug":"press-militar-con-mancuernas","default_metric":"weight"},
          {"name":"Press militar en multipower","muscle_group":"Hombro","slug":"press-militar-en-multipower","default_metric":"weight"},
          {"name":"Press en máquina","muscle_group":"Hombro","slug":"press-en-maquina-hombro","default_metric":"weight"},
          {"name":"Elevaciones laterales con mancuernas","muscle_group":"Hombro","slug":"elevaciones-laterales-con-mancuernas","default_metric":"weight"},
          {"name":"Elevaciones laterales en polea","muscle_group":"Hombro","slug":"elevaciones-laterales-en-polea","default_metric":"weight"},
          {"name":"Elevaciones laterales en máquina","muscle_group":"Hombro","slug":"elevaciones-laterales-en-maquina","default_metric":"weight"},
          {"name":"Elevaciones frontales con disco","muscle_group":"Hombro","slug":"elevaciones-frontales-con-disco","default_metric":"weight"},
          {"name":"Elevaciones frontales con mancuernas","muscle_group":"Hombro","slug":"elevaciones-frontales-con-mancuernas","default_metric":"weight"},
          {"name":"Elevaciones posteriores con mancuernas","muscle_group":"Hombro","slug":"elevaciones-posteriores-con-mancuernas","default_metric":"weight"},
          {"name":"Pájaros en banco inclinado","muscle_group":"Hombro","slug":"pajaros-en-banco-inclinado","default_metric":"weight"},
          {"name":"Pájaros en máquina","muscle_group":"Hombro","slug":"pajaros-en-maquina","default_metric":"weight"},
          {"name":"Face pull en polea","muscle_group":"Hombro","slug":"face-pull-en-polea-hombro","default_metric":"weight"},
          {"name":"Encogimientos con barra","muscle_group":"Hombro","slug":"encogimientos-con-barra","default_metric":"weight"},
          {"name":"Encogimientos con mancuernas","muscle_group":"Hombro","slug":"encogimientos-con-mancuernas","default_metric":"weight"},
          {"name":"Remo al mentón con barra","muscle_group":"Hombro","slug":"remo-al-menton-con-barra","default_metric":"weight"},
          {"name":"Correr en cinta","muscle_group":"Cardio","slug":"correr-en-cinta","default_metric":"time"},
          {"name":"Correr al aire libre","muscle_group":"Cardio","slug":"correr-al-aire-libre","default_metric":"time"},
          {"name":"Caminata en cinta","muscle_group":"Cardio","slug":"caminata-en-cinta","default_metric":"time"},
          {"name":"Bicicleta estática","muscle_group":"Cardio","slug":"bicicleta-estatica","default_metric":"time"},
          {"name":"Bicicleta de spinning","muscle_group":"Cardio","slug":"bicicleta-de-spinning","default_metric":"time"},
          {"name":"Bicicleta reclinada","muscle_group":"Cardio","slug":"bicicleta-reclinada","default_metric":"time"},
          {"name":"Elíptica","muscle_group":"Cardio","slug":"eliptica","default_metric":"time"},
          {"name":"Remo en máquina","muscle_group":"Cardio","slug":"remo-en-maquina-cardio","default_metric":"time"},
          {"name":"Saltar cuerda","muscle_group":"Cardio","slug":"saltar-cuerda","default_metric":"time"},
          {"name":"Escaladora","muscle_group":"Cardio","slug":"escaladora","default_metric":"time"},
          {"name":"HIIT en cinta","muscle_group":"Cardio","slug":"hiit-en-cinta","default_metric":"time"},
          {"name":"HIIT en bicicleta","muscle_group":"Cardio","slug":"hiit-en-bicicleta","default_metric":"time"},
          {"name":"Crunch en suelo","muscle_group":"Abdomen","slug":"crunch-en-suelo","default_metric":"weight"},
          {"name":"Crunch en máquina","muscle_group":"Abdomen","slug":"crunch-en-maquina","default_metric":"weight"},
          {"name":"Crunch en polea","muscle_group":"Abdomen","slug":"crunch-en-polea","default_metric":"weight"},
          {"name":"Crunch inverso","muscle_group":"Abdomen","slug":"crunch-inverso","default_metric":"weight"},
          {"name":"Elevación de piernas en banco","muscle_group":"Abdomen","slug":"elevacion-de-piernas-en-banco","default_metric":"weight"},
          {"name":"Elevación de piernas colgado","muscle_group":"Abdomen","slug":"elevacion-de-piernas-colgado","default_metric":"weight"},
          {"name":"Elevación de rodillas colgado","muscle_group":"Abdomen","slug":"elevacion-de-rodillas-colgado","default_metric":"weight"},
          {"name":"Plancha frontal","muscle_group":"Abdomen","slug":"plancha-frontal","default_metric":"weight"},
          {"name":"Plancha lateral","muscle_group":"Abdomen","slug":"plancha-lateral","default_metric":"weight"},
          {"name":"Russian twist con peso","muscle_group":"Abdomen","slug":"russian-twist-con-peso","default_metric":"weight"},
          {"name":"Mountain climbers","muscle_group":"Abdomen","slug":"mountain-climbers","default_metric":"weight"},
          {"name":"Ab wheel","muscle_group":"Abdomen","slug":"ab-wheel","default_metric":"weight"},
          {"name":"Toques de talón","muscle_group":"Abdomen","slug":"toques-de-talon","default_metric":"weight"},
          {"name":"V-ups","muscle_group":"Abdomen","slug":"v-ups","default_metric":"weight"},
          {"name":"Sit-ups","muscle_group":"Abdomen","slug":"sit-ups","default_metric":"weight"},
          {"name":"Estiramiento de cuádriceps de pie","muscle_group":"Flexibilidad","slug":"estiramiento-de-cuadriceps-de-pie","default_metric":"time"},
          {"name":"Estiramiento de isquiotibiales sentado","muscle_group":"Flexibilidad","slug":"estiramiento-de-isquiotibiales-sentado","default_metric":"time"},
          {"name":"Estiramiento de isquiotibiales de pie","muscle_group":"Flexibilidad","slug":"estiramiento-de-isquiotibiales-de-pie","default_metric":"time"},
          {"name":"Estiramiento de glúteos tumbado","muscle_group":"Flexibilidad","slug":"estiramiento-de-gluteos-tumbado","default_metric":"time"},
          {"name":"Estiramiento de glúteos sentado","muscle_group":"Flexibilidad","slug":"estiramiento-de-gluteos-sentado","default_metric":"time"},
          {"name":"Estiramiento de gemelos en pared","muscle_group":"Flexibilidad","slug":"estiramiento-de-gemelos-en-pared","default_metric":"time"},
          {"name":"Estiramiento de pecho en pared","muscle_group":"Flexibilidad","slug":"estiramiento-de-pecho-en-pared","default_metric":"time"},
          {"name":"Estiramiento de espalda en el suelo","muscle_group":"Flexibilidad","slug":"estiramiento-de-espalda-en-el-suelo","default_metric":"time"},
          {"name":"Estiramiento de hombros cruzado","muscle_group":"Flexibilidad","slug":"estiramiento-de-hombros-cruzado","default_metric":"time"},
          {"name":"Movilidad de cadera en círculos","muscle_group":"Flexibilidad","slug":"movilidad-de-cadera-en-circulos","default_metric":"time"},
          {"name":"Movilidad de hombros con banda","muscle_group":"Flexibilidad","slug":"movilidad-de-hombros-con-banda","default_metric":"time"},
          {"name":"Movilidad de columna en gato-vaca","muscle_group":"Flexibilidad","slug":"movilidad-de-columna-en-gato-vaca","default_metric":"time"},
          {"name":"Foam roller cuádriceps","muscle_group":"Flexibilidad","slug":"foam-roller-cuadriceps","default_metric":"time"},
          {"name":"Foam roller isquiotibiales","muscle_group":"Flexibilidad","slug":"foam-roller-isquiotibiales","default_metric":"time"},
          {"name":"Foam roller espalda","muscle_group":"Flexibilidad","slug":"foam-roller-espalda","default_metric":"time"}
        ]
        $json$::jsonb
    ) as item(name text, muscle_group text, slug text, default_metric text)
)
insert into public.exercises (slug, name, muscle_group, default_metric, instructions)
select
    seed.slug,
    seed.name,
    seed.muscle_group,
    seed.default_metric,
    ''
from seed
on conflict (slug) do update
set
    name = excluded.name,
    muscle_group = excluded.muscle_group,
    default_metric = excluded.default_metric;